# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='face.proto',
  package='face',
  syntax='proto3',
  serialized_options=b'\n\016com.proto.faceP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nface.proto\x12\x04\x66\x61\x63\x65\"A\n\x16\x46\x61\x63\x65RecognitionRequest\x12\x11\n\ttimeStamp\x18\x01 \x01(\x03\x12\x14\n\x0cvideoContent\x18\x02 \x03(\x0c\"&\n\x17\x46\x61\x63\x65RecognitionResponse\x12\x0b\n\x03num\x18\x01 \x01(\x03\x32]\n\x0b\x46\x61\x63\x65Service\x12N\n\rRecognizeFace\x12\x1c.face.FaceRecognitionRequest\x1a\x1d.face.FaceRecognitionResponse\"\x00\x42\x12\n\x0e\x63om.proto.faceP\x01\x62\x06proto3'
)




_FACERECOGNITIONREQUEST = _descriptor.Descriptor(
  name='FaceRecognitionRequest',
  full_name='face.FaceRecognitionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='face.FaceRecognitionRequest.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='videoContent', full_name='face.FaceRecognitionRequest.videoContent', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=85,
)


_FACERECOGNITIONRESPONSE = _descriptor.Descriptor(
  name='FaceRecognitionResponse',
  full_name='face.FaceRecognitionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='face.FaceRecognitionResponse.num', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['FaceRecognitionRequest'] = _FACERECOGNITIONREQUEST
DESCRIPTOR.message_types_by_name['FaceRecognitionResponse'] = _FACERECOGNITIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FaceRecognitionRequest = _reflection.GeneratedProtocolMessageType('FaceRecognitionRequest', (_message.Message,), {
  'DESCRIPTOR' : _FACERECOGNITIONREQUEST,
  '__module__' : 'face_pb2'
  # @@protoc_insertion_point(class_scope:face.FaceRecognitionRequest)
  })
_sym_db.RegisterMessage(FaceRecognitionRequest)

FaceRecognitionResponse = _reflection.GeneratedProtocolMessageType('FaceRecognitionResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACERECOGNITIONRESPONSE,
  '__module__' : 'face_pb2'
  # @@protoc_insertion_point(class_scope:face.FaceRecognitionResponse)
  })
_sym_db.RegisterMessage(FaceRecognitionResponse)


DESCRIPTOR._options = None

_FACESERVICE = _descriptor.ServiceDescriptor(
  name='FaceService',
  full_name='face.FaceService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=127,
  serialized_end=220,
  methods=[
  _descriptor.MethodDescriptor(
    name='RecognizeFace',
    full_name='face.FaceService.RecognizeFace',
    index=0,
    containing_service=None,
    input_type=_FACERECOGNITIONREQUEST,
    output_type=_FACERECOGNITIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACESERVICE)

DESCRIPTOR.services_by_name['FaceService'] = _FACESERVICE

# @@protoc_insertion_point(module_scope)
