# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import face_pb2 as face__pb2


class FaceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeFace = channel.unary_unary(
                '/face.FaceService/RecognizeFace',
                request_serializer=face__pb2.FaceRecognitionRequest.SerializeToString,
                response_deserializer=face__pb2.FaceRecognitionResponse.FromString,
                )


class FaceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecognizeFace(self, request, context):
        """unary API
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeFace': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeFace,
                    request_deserializer=face__pb2.FaceRecognitionRequest.FromString,
                    response_serializer=face__pb2.FaceRecognitionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'face.FaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecognizeFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/face.FaceService/RecognizeFace',
            face__pb2.FaceRecognitionRequest.SerializeToString,
            face__pb2.FaceRecognitionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
