# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movie.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='movie.proto',
  package='movie',
  syntax='proto3',
  serialized_options=b'\n\017com.proto.movieP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bmovie.proto\x12\x05movie\"\xea\x01\n\x05Movie\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12!\n\x06genres\x18\x03 \x03(\x0e\x32\x11.movie.MovieGenre\x12%\n\tdirectors\x18\x04 \x03(\x0b\x32\x12.movie.MoviePerson\x12#\n\x07writers\x18\x05 \x03(\x0b\x32\x12.movie.MoviePerson\x12!\n\x05stars\x18\x06 \x03(\x0b\x32\x12.movie.MoviePerson\x12\x1a\n\x12year_of_production\x18\x07 \x01(\x05\x12\x18\n\x10\x64uration_minutes\x18\x08 \x01(\x05\"4\n\x0bMoviePerson\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\"$\n\x10\x41\x64\x64MovieResponse\x12\x10\n\x08movie_id\x18\x01 \x01(\t\".\n\x19\x41\x64\x64MultipleMoviesResponse\x12\x11\n\tmovie_ids\x18\x01 \x03(\t\"3\n\tMovieNote\x12\x10\n\x08movie_id\x18\x01 \x01(\t\x12\x14\n\x0cmovie_rating\x18\x02 \x01(\x05\"A\n\x16\x46\x61\x63\x65RecognitionRequest\x12\x11\n\ttimeStamp\x18\x01 \x01(\x03\x12\x14\n\x0cvideoContent\x18\x02 \x03(\x0c\"&\n\x17\x46\x61\x63\x65RecognitionResponse\x12\x0b\n\x03num\x18\x01 \x01(\x03*k\n\nMovieGenre\x12\n\n\x06\x41\x43TION\x10\x00\x12\n\n\x06\x43OMEDY\x10\x01\x12\t\n\x05\x44RAMA\x10\x02\x12\n\n\x06HORROR\x10\x03\x12\n\n\x06SCI_FI\x10\x04\x12\x0c\n\x08THRILLER\x10\x05\x12\x07\n\x03WAR\x10\x06\x12\x0b\n\x07WESTERN\x10\x07\x32_\n\x0b\x46\x61\x63\x65Service\x12P\n\rRecognizeFace\x12\x1d.movie.FaceRecognitionRequest\x1a\x1e.movie.FaceRecognitionResponse\"\x00\x32\xbf\x01\n\x0cMovieService\x12\x33\n\x08\x41\x64\x64Movie\x12\x0c.movie.Movie\x1a\x17.movie.AddMovieResponse\"\x00\x12G\n\x11\x41\x64\x64MultipleMovies\x12\x0c.movie.Movie\x1a .movie.AddMultipleMoviesResponse\"\x00(\x01\x12\x31\n\tMovieChat\x12\x0c.movie.Movie\x1a\x10.movie.MovieNote\"\x00(\x01\x30\x01\x42\x13\n\x0f\x63om.proto.movieP\x01\x62\x06proto3'
)

_MOVIEGENRE = _descriptor.EnumDescriptor(
  name='MovieGenre',
  full_name='movie.MovieGenre',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACTION', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMEDY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DRAMA', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HORROR', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SCI_FI', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='THRILLER', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WAR', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WESTERN', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=559,
  serialized_end=666,
)
_sym_db.RegisterEnumDescriptor(_MOVIEGENRE)

MovieGenre = enum_type_wrapper.EnumTypeWrapper(_MOVIEGENRE)
ACTION = 0
COMEDY = 1
DRAMA = 2
HORROR = 3
SCI_FI = 4
THRILLER = 5
WAR = 6
WESTERN = 7



_MOVIE = _descriptor.Descriptor(
  name='Movie',
  full_name='movie.Movie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='movie.Movie.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='movie.Movie.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='genres', full_name='movie.Movie.genres', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='directors', full_name='movie.Movie.directors', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='writers', full_name='movie.Movie.writers', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stars', full_name='movie.Movie.stars', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='year_of_production', full_name='movie.Movie.year_of_production', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration_minutes', full_name='movie.Movie.duration_minutes', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=257,
)


_MOVIEPERSON = _descriptor.Descriptor(
  name='MoviePerson',
  full_name='movie.MoviePerson',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='movie.MoviePerson.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='movie.MoviePerson.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=311,
)


_ADDMOVIERESPONSE = _descriptor.Descriptor(
  name='AddMovieResponse',
  full_name='movie.AddMovieResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='movie_id', full_name='movie.AddMovieResponse.movie_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=349,
)


_ADDMULTIPLEMOVIESRESPONSE = _descriptor.Descriptor(
  name='AddMultipleMoviesResponse',
  full_name='movie.AddMultipleMoviesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='movie_ids', full_name='movie.AddMultipleMoviesResponse.movie_ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=397,
)


_MOVIENOTE = _descriptor.Descriptor(
  name='MovieNote',
  full_name='movie.MovieNote',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='movie_id', full_name='movie.MovieNote.movie_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='movie_rating', full_name='movie.MovieNote.movie_rating', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=450,
)


_FACERECOGNITIONREQUEST = _descriptor.Descriptor(
  name='FaceRecognitionRequest',
  full_name='movie.FaceRecognitionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='movie.FaceRecognitionRequest.timeStamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='videoContent', full_name='movie.FaceRecognitionRequest.videoContent', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=517,
)


_FACERECOGNITIONRESPONSE = _descriptor.Descriptor(
  name='FaceRecognitionResponse',
  full_name='movie.FaceRecognitionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='movie.FaceRecognitionResponse.num', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=519,
  serialized_end=557,
)

_MOVIE.fields_by_name['genres'].enum_type = _MOVIEGENRE
_MOVIE.fields_by_name['directors'].message_type = _MOVIEPERSON
_MOVIE.fields_by_name['writers'].message_type = _MOVIEPERSON
_MOVIE.fields_by_name['stars'].message_type = _MOVIEPERSON
DESCRIPTOR.message_types_by_name['Movie'] = _MOVIE
DESCRIPTOR.message_types_by_name['MoviePerson'] = _MOVIEPERSON
DESCRIPTOR.message_types_by_name['AddMovieResponse'] = _ADDMOVIERESPONSE
DESCRIPTOR.message_types_by_name['AddMultipleMoviesResponse'] = _ADDMULTIPLEMOVIESRESPONSE
DESCRIPTOR.message_types_by_name['MovieNote'] = _MOVIENOTE
DESCRIPTOR.message_types_by_name['FaceRecognitionRequest'] = _FACERECOGNITIONREQUEST
DESCRIPTOR.message_types_by_name['FaceRecognitionResponse'] = _FACERECOGNITIONRESPONSE
DESCRIPTOR.enum_types_by_name['MovieGenre'] = _MOVIEGENRE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Movie = _reflection.GeneratedProtocolMessageType('Movie', (_message.Message,), {
  'DESCRIPTOR' : _MOVIE,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:movie.Movie)
  })
_sym_db.RegisterMessage(Movie)

MoviePerson = _reflection.GeneratedProtocolMessageType('MoviePerson', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEPERSON,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:movie.MoviePerson)
  })
_sym_db.RegisterMessage(MoviePerson)

AddMovieResponse = _reflection.GeneratedProtocolMessageType('AddMovieResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDMOVIERESPONSE,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:movie.AddMovieResponse)
  })
_sym_db.RegisterMessage(AddMovieResponse)

AddMultipleMoviesResponse = _reflection.GeneratedProtocolMessageType('AddMultipleMoviesResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDMULTIPLEMOVIESRESPONSE,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:movie.AddMultipleMoviesResponse)
  })
_sym_db.RegisterMessage(AddMultipleMoviesResponse)

MovieNote = _reflection.GeneratedProtocolMessageType('MovieNote', (_message.Message,), {
  'DESCRIPTOR' : _MOVIENOTE,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:movie.MovieNote)
  })
_sym_db.RegisterMessage(MovieNote)

FaceRecognitionRequest = _reflection.GeneratedProtocolMessageType('FaceRecognitionRequest', (_message.Message,), {
  'DESCRIPTOR' : _FACERECOGNITIONREQUEST,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:movie.FaceRecognitionRequest)
  })
_sym_db.RegisterMessage(FaceRecognitionRequest)

FaceRecognitionResponse = _reflection.GeneratedProtocolMessageType('FaceRecognitionResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACERECOGNITIONRESPONSE,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:movie.FaceRecognitionResponse)
  })
_sym_db.RegisterMessage(FaceRecognitionResponse)


DESCRIPTOR._options = None

_FACESERVICE = _descriptor.ServiceDescriptor(
  name='FaceService',
  full_name='movie.FaceService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=668,
  serialized_end=763,
  methods=[
  _descriptor.MethodDescriptor(
    name='RecognizeFace',
    full_name='movie.FaceService.RecognizeFace',
    index=0,
    containing_service=None,
    input_type=_FACERECOGNITIONREQUEST,
    output_type=_FACERECOGNITIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACESERVICE)

DESCRIPTOR.services_by_name['FaceService'] = _FACESERVICE


_MOVIESERVICE = _descriptor.ServiceDescriptor(
  name='MovieService',
  full_name='movie.MovieService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=766,
  serialized_end=957,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddMovie',
    full_name='movie.MovieService.AddMovie',
    index=0,
    containing_service=None,
    input_type=_MOVIE,
    output_type=_ADDMOVIERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddMultipleMovies',
    full_name='movie.MovieService.AddMultipleMovies',
    index=1,
    containing_service=None,
    input_type=_MOVIE,
    output_type=_ADDMULTIPLEMOVIESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MovieChat',
    full_name='movie.MovieService.MovieChat',
    index=2,
    containing_service=None,
    input_type=_MOVIE,
    output_type=_MOVIENOTE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MOVIESERVICE)

DESCRIPTOR.services_by_name['MovieService'] = _MOVIESERVICE

# @@protoc_insertion_point(module_scope)
